### ISSUE TITLE
Kann Simulator nicht starten

### ISSUE THREAD

**Issue by ErdoganSeref** [informatiCup/informatiCup2022#11]
Wenn ich mittels make den Simulator starten will dann kriege ich folgende Fehlermeldung.

make
rm -rf build-win build-linux build-darwin dist
mkdir build-win
mkdir build-linux
mkdir build-darwin
CGO_ENABLED=0 GOOS=windows go build -o build-win/bahn-simulator.exe
/bin/sh: Zeile 1: go: Kommando nicht gefunden.
make: *** [Makefile:10: dist] Fehler 127

**Comment by Top-Ranger** [comment]
Moin,

das zeigt für mich, dass die Programmiersprache [go](https://golang.org/doc/install) bei dir nicht installiert ist.
Die Makefile wurde bisher nur auf Linux getestet, der Befehl ```go build``` sollte aber (wenn go installiert ist) immer funktionieren.

**Comment by ErdoganSeref** [comment]
Ok. Ich habe go installiert. Jetzt hat make funktioniert. Im sub directory
build-linux gibt es eine bahn-simulator.exe wenn ich sie ohne Parameter
ausführe kriege ich 0 als Rückgabe. Muss ich also der bahn-simulator.exe
den input.txt und output.txt als Parameter übergeben?

Am Sa., 30. Okt. 2021 um 19:34 Uhr schrieb Marcus Soll <
***@***.***>:

**Comment by bitflipp** [comment]
Kommandozeilenparameter `--help`.

**Comment by ErdoganSeref** [comment]
Ok. Jetzt hat es funktioniert. Jetzt verstehe ich auch wofür das Tool da
ist. Danke.

Am Sa., 30. Okt. 2021 um 20:37 Uhr schrieb Philipp Naumann <
***@***.***>:
