### ISSUE TITLE
Bereits angemeldetes Team löschen

### ISSUE THREAD

**Issue by FiniH** [informatiCup/informatiCup2022#12]
Moin zusammen,
unserem Teamcaptain ist leider der Fehler passiert, unser Team bereits fest anzumelden bevor wir vollständig waren. Gibt es die Möglichkeit, das bereits angemeldete Team noch zu löschen oder müssen wir jetzt alle unsere Benutzerprofile löschen und neu anlegen, damit wir uns in der richtigen Konstellation anmelden können?

**Comment by AlexPaar** [comment]
Hallo Finja, kein Problem. Ich habe Euer Team gerade gelöscht.

**Comment by FiniH** [comment]
Super, dankeschön :)
