### ISSUE TITLE
Frage zur Enviroment

### ISSUE THREAD

**Issue by finitearth** [informatiCup/informatiCup2022#13]
Hallo zusammen :) ,

### erstmal vielen Dank für den tollen Wettbewerb, wir sind richtig motiviert💯
Nun zu unserer Frage: Inwiefern sind die Beispiel-Inputfiles vergleichbar mit den endgültigen Inputfiles für den Wettbewerb, mit dem unser Algorithmus getestet werden soll? Können wir davon ausgehen, dass die Anzahl der Züge/Bahnhöfe/Passagiere sich in diesem Bereich befinden können? Wenn nicht, von welchen Dimensionen könnten wir in etwa ausgehen ***(ist das gesamte Streckennetz von BaWü realitisch)***?

![Grafik](https://user-images.githubusercontent.com/19229952/140491482-3b1232e3-fb56-43aa-8499-b5dd5b49b089.png)
_Edit: so sieht eine Darstellung eines unserer Streckennetze aus._

Vielen Dank im Voraus 👍 

Mit lieben Grüßen
Luisa, Pascal, Tom

**Comment by Top-Ranger** [comment]
Moin,
wir planen, auch größere Netze als Eingabe zu verwenden. Ein Netz wie das "Streckennetz von BaWü" kann ich mir gut als eine Eingabe vorstellen.

Viel Spaß bei der Aufgabe! Verliert nicht die Motivation.
