### ISSUE TITLE
Bahn-Simulator

### ISSUE THREAD

**Issue by sedengel25** [informatiCup/informatiCup2022#14]
Hallöchen,

leider sind wir uns noch etwas unschlüssig wie genau der Bahn-Simulator aussehen soll. "go build" hat funktioniert, genauso wie das Übergeben der input- und output-files an "bahn-simulator.exe". Jetzt gibt es ja zusätzlich noch die Möglichkeit ein "pprof profile" zu erzeugen. Wenn ich versuche das entstandene File zu visualisieren mittels "go tool pprof <sourcefile>" (und anschließend "web" im interactive mode) bekomme ich die Meldung "No samples were found with the default sample value type". Was genau hat es damit auf sich? Eigentlich hatte ich erwartet, dass die Simulation über das MOD-file geschieht, welches ich aber leider nicht öffnen kann. Weiß jemand wie ich mir eine Probleminstanz bzw. deren Lösung simulieren lassen kann?

Vielen Dank im Voraus und viele Grüße!

Sebastian, Alex & Vincent

**Comment by Top-Ranger** [comment]
Moin,
pprof benötigt ihr nur, wenn ihr den Simulator selber optimieren wollt. Ihr könnt den Flag ignorieren. Siehe auch: https://go.dev/blog/pprof
Die go.mod-Datei ist für die go-Module zuständig, ähnlich wie z.B. eine package.json-Datei. Siehe auch: https://go.dev/blog/using-go-modules
Ich hoffe, das hilft euch weiter.
