### ISSUE TITLE
Einheitliche Ausgabe des Bahnsimulators

### ISSUE THREAD

**Issue by BlobbyBob** [informatiCup/informatiCup2022#15]
Aktuell gibt der Bahnsimulator im Fehlerfall in Abhängigkeit vom konkreten Fehler eine kurze Info entweder über `stdout` oder `stderr` aus. Es wäre schön, wenn man das einheitlich gestalten könnte, z.B. durch ein
```go
log.SetOutput(os.Stdout)
```
oder durch ein
```go
fmt.Fprintln(os.Stderr, ...)
```
bei allen `fmt.Println` Aufrufen.

**Comment by Top-Ranger** [comment]
Moin,

ich habe die Ausgabe vereinheitlicht.

Fehler bei Validation = stdout
Fehler bei Ausführung = stderr.

Vielen Dank für den Vorschlag!
