### ISSUE TITLE
Merkwürdige Inputs von der Teams CI

### ISSUE THREAD

**Issue by LeCoup2000** [informatiCup/informatiCup2022#17]
Moin, wir haben Eingaben von der CI bekommen, bei welchen wir nicht sicher sind, ob sie gewollt sind bzw. wie wir darauf reagieren sollen.

# Input 1:
[Stations]
Start 7
Q1 904564684684684635416848084684151687864561564984651320203549654132165486416513210635484561321023063574869874846515316846516534896451219657485635419687465168416547987468541651352165498747509827982698726897269573052835929
R1 9
R2 9
R3 6
R4 8
End 7

[Lines]
SQ1 Start Q1 12 8748
Q1E Q1 End 12 8847

SR1 Start R1 4 8975
R1R2 R1 R2 4 4752
R2R3 R2 R3 4 7651
R3R4 R3 R4 4 5891
R4E R4 End 4 9841

[Trains]
Train Start 3 5645

[Passengers]
Passenger Start End 5645 8

# input2:
Invalid input

# Die Fragen dazu:
Ist Eingabe 1 mit einer so großen Zahl tatsächlich gewollt und falls ja, soll sie in dieser Größe betrachtet werden?
Wie soll auf invalide Inputs reagiert werden?

**Comment by Top-Ranger** [comment]
Die Eingabe **input1** entspricht der Spezifikation der Aufgabe und sollte von jeder Lösung verarbeitet werden können.
Bei der Eingabe **input2** handelt es sich um einen kurzzeitigen Fehler im CI, der behoben sein sollte.

**Comment by LeCoup2000** [comment]
Danke für die schnelle Antwort
