### ISSUE TITLE
Benötigt das CI-System für das TESTEN ein docker-Image?

### ISSUE THREAD

**Issue by lukas2701** [informatiCup/informatiCup2022#18]
Ist für das Testen mit dem CI-System erforderlich, ein docker-Image bzw. eine docker-File usw. auf das Teammates Repository `ci@ci.informaticup.de:/repo` zu pushen?

**Comment by Top-Ranger** [comment]
Moin,

das Repo könnt ihr jederzeit nutzen, für das Testen eurer Lösung wird ein Dockerfile benötigt.
Basierend auf eurer Frage habe ich die [ICUPCI.md](https://github.com/informatiCup/informatiCup2022/blob/main/ICUPCI.md#continuous-integration) entsprechend erweitert.
