### ISSUE TITLE
Error: failed to clone repository: failed to determine commit ID

### ISSUE THREAD

**Issue by lukas2701** [informatiCup/informatiCup2022#19]
Wir haben unseren Code (mit einer entsprechenden **Dockerfile**) auf unser Repository `ci@ci.informaticup.de:/repo` gepusht.
Dennoch tritt in Teammates unter Team folgender Fehler auf:
`failed to clone repository: failed to determine commit ID`

Nach ausführen von `git log` in der Branch `main` liegen jedoch commits vor.

**Comment by bitflipp** [comment]
Wie ist der Zeitstempel des Ergebnisses (abzulesen in Teammates)? Der Build-Vorgang wird zeitgesteuert angestoßen - ca. alle 24 Stunden, nicht bei jedem Push.

**Comment by lukas2701** [comment]
Zeitstempel:
```
Start: 15.12.2021 18:07:16
Ende: 15.12.2021 18:07:16
```
Gepusht wurde das letzte mal auf jeden Fall vor 18:00 Uhr am 15.12.2021.

**Comment by bitflipp** [comment]
Beim Klonen tritt folgende Fehlermeldung auf:

```warning: remote HEAD refers to nonexistent ref, unable to checkout.```

Bitte versucht `git push --mirror ci@ci.informaticup.de:/repo` und postet die Ausgabe.

**Comment by lukas2701** [comment]
@bitflipp 
Ausgabe:

Enumerating objects: 10, done.
Counting objects: 100% (10/10), done.
Delta compression using up to 4 threads
Compressing objects: 100% (7/7), done.
Writing objects: 100% (7/7), 1.04 KiB | 530.00 KiB/s, done.
Total 7 (delta 4), reused 0 (delta 0), pack-reused 0
To ci.informaticup.de:/repo
 + 0eb02c6...c06a2ba main -> main (forced update)
   a2cd83e..c06a2ba  main_backup_before_stdin -> main_backup_before_stdin
   5fa5a2f..c06a2ba  origin/HEAD -> origin/HEAD
   5fa5a2f..c06a2ba  origin/main -> origin/main
   a2cd83e..c06a2ba  origin/main_backup_before_stdin -> origin/main_backup_before_stdin

**Comment by bitflipp** [comment]
Danke. Das CI geht (undokumentiert) davon aus, dass ```HEAD``` auf ```master``` zeigt. Wir werden das CI dahingehend erweitern, dass auch ```main``` akzeptiert (und sogar bevorzugt) wird und dies auch entsprechend dokumentieren.

**Comment by bitflipp** [comment]
Das CI arbeitet jetzt auf Branch ```main``` mit ```master``` als Fallback, s. auch [README](https://github.com/informatiCup/informatiCup2022/blob/main/ICUPCI.md).
