### ISSUE TITLE
StandardInput implementieren

### ISSUE THREAD

**Issue by Jessi96LM** [informatiCup/informatiCup2022#2]
Es muss ein Standardinput implementiert werden

**Comment by Top-Ranger** [comment]
Moin,
beim Standardinput handelt es sich über die "normale" Eingabe in einen Prozess. In den meisten Programmiersprachen wird dies über eine virtuelle Datei gelöst (z.b. [c](https://docs.microsoft.com/de-de/cpp/c-runtime-library/stdin-stdout-stderr?view=msvc-160), [python](https://docs.python.org/3/library/sys.html#sys.stdin), [go](https://pkg.go.dev/os#pkg-variables)).

Wenn du einen Befehl über die Konsole startest und dann etwas eingibst, so ist das in der Regel der Standardinput.

Ich hoffe, dass die Kurzbeschreibung hilfreich ist.
