### ISSUE TITLE
Minimal Gesamtverspätung

### ISSUE THREAD

**Issue by cbl** [informatiCup/informatiCup2022#22]
Im [informatiCup 2022 - Abfahrt!.pdf](https://github.com/informatiCup/informatiCup2022/blob/main/informatiCup%202022%20-%20Abfahrt!.pdf)  auf Seite 6 ist beschrieben, dass die **Minimale Gesamtverspätung** bewertet wird. Meine Frage ist ob negative Verspätungen (also zu früh ankommende Passagiere) positiv in die Bewertung fallen würden oder ob die Gesamtverspätung die Summe der Verspätungen aller zu spät kommenden Passagiere ist.

Hier nochmal anders beschrieben:

- `d_ges` : Gesamtverspätung (d=delay)
- `P` : Menge mit Passagieren
- `P_l` : Menge aller zu spät kommenden Passagiere
- `d_p` : Verspätung von Passagier 

1. Alle **Ankunftszeiten** werden summiert

```
d_ges = sum(d_p) | wobei p in P
```

2. Alle **Verspätungen** werden summiert

```
d_ges = sum(d_p) | wobei p in P_l
```

**Comment by Top-Ranger** [comment]
Zu früh ankommende Personen bringen keinen Vorteil, die minimale Gesamtverspätung beträgt 0.
