### ISSUE TITLE
Erwartete Dauer für die Erstellung/Berechnung des Fahrplans (bezüglich der Bewertung)

### ISSUE THREAD

**Issue by lukas2701** [informatiCup/informatiCup2022#23]
@Top-Ranger @bitflipp @jonico @MichaelChat @AlexPaar 
Gibt es ein **Zeitlimit** für die Erstellung/Berechnung des Fahrplans? Bzw. gibt es überhaupt einen **erwarteten** Zeitrahmen?
Bei welcher Zeit/Dauer (z.B. für den Test **large**) liegt die Bewertung noch im "grünen" Bereich?
Sind da z.B. 6 Minuten das Limit **oder** eher 20 Minuten (für eine entsprechend optimalere Lösung)?

**Comment by jfreyberg** [comment]
In der Aufgabenstellung steht hierzu:

> Die Qualität der Lösung wird anhand der Gesamtverspätung aller Passagiere ermittelt.

und 

> **Minimale Gesamtverspätung:** Wie hoch ist die Verspätung aller Passagiere nach dem berechneten Plan?
**Rechenzeit:** Wie lange benötigt Eure Software, um die Lösung zu berechnen?

Unklar bleiben aber die folgenden Fragen:

- Gibt es ein Zeitlimit? Falls ja, wie viel Rechenzeit steht maximal zur Verfügung? Falls nicht, wie wird mit extrem langsamen Lösungen umgegangen?
- In welchem Verhältnis stehen die beiden Kriterien (Rechenzeit und Gesamtversptäung)? Ist ein Loss von 30 nach 5 Minuten oder ein Loss von 50 nach 2 Minuten besser? Gibt es hier eine Metrik, die beide Kriterien berücksichtigt?

Ohne Klärung dieser Fragen ist es m.M.n. nicht möglich das Problem adäquat zu lösen, da nicht klar ist hinsichtlich welcher der beiden Metriken optimiert werden soll.

**Comment by Top-Ranger** [comment]
Moin,

es ist eure Aufgabe, beide Aspekte zusammen zu bringen. Wir geben euch kein hartes Limit an die Berechnungszeit, jedoch sollte eure Berechnungszeit angemessen sein. Schaut euch z.B. *use cases* an (Soll euer Programm "just in time" Fahrpläne erstellen? Sollen die Fahrpläne eine Woche vorher erstellt werden? etc.). Entsprechende Abwägungen und Rahmenbedingungen sollten dabei in eurer Ausarbeitung auftauchen. Am besten ist natürlich eine schnelle **und** gute Lösung :slightly_smiling_face:

Bei der Hardware, auf der eure Software ausgeführt wird, könnt ihr davon ausgehen, dass es sich um moderne Mehrkernprozessor-Computer mit einigen GB RAM und keiner speziellen Grafikkarte handelt. Es ist möglich, dass die Systeme virtualisiert sind.

Bitte beachtet, dass dies nicht das einzige Wertungskriterium ist. Die (theoretische) Ausarbeitung, die Benutzerführung und die Softwarequalität sind genau so wichtig.
