### ISSUE TITLE
Tests ausgesetzt?

### ISSUE THREAD

**Issue by lukas2701** [informatiCup/informatiCup2022#24]
@Top-Ranger @bitflipp 
Seit dem **19.12** wurden **keine** automatisierten Tests mehr durch das CI-System durchgeführt (zumindestens bei uns) trotz neuer Commits/Pushs. Ist dies so beabsichtigt?

**Comment by Top-Ranger** [comment]
Moin,

vielen Dank für den Hinweis. Die Tests sind tatsächlich weiter gelaufen, nur gab es im Hintergrund ein paar Probleme bei der Übertragung der Ergebnisse nach Teammates. Mittlerweile sollten neue Ergebnisse auch wieder angezeigt werden.

Sollten weiterhin Probleme auftauchen oder neue Probleme auftauchen sagt gerne Bescheid, wir sind für jeden Hinweis dankbar,
