### ISSUE TITLE
Bahn-Simulator in die Abgabe mit einbinden erlaubt?

### ISSUE THREAD

**Issue by lukas2701** [informatiCup/informatiCup2022#25]
@Top-Ranger @bitflipp 
Ist es erlaubt bzw. gestattet den Bahn-Simulator in die Abgabe bzw. das Repository mit einzubeziehen?

**Comment by Top-Ranger** [comment]
Moin,

ihr dürft den Code mit einbeziehen, siehe [FAQ](https://informaticup.github.io/competition/30-faq):
>Darf ich (öffentlich) verfügbaren Code verwenden, etwa aus öffentlichen GitHub-Repositorys oder Implementierungen von Forschungsarbeiten?
>
>Ihr dürft Eure Lösung auf jeder Software aufbauen oder damit ermöglichen, die für jedermann kostenlos verfügbar ist und keine besonderen Einschränkungen (wie nur X mal ausführen) hat. Sollte es eine Option geben, weitere Fähigkeiten, Module, etc. zu erwerben, so darf nur die kostenlose und keine erweiterte Version verwendet werden. Nennt auch korrekt und vollständig die Autoren dieser Software und beachtet mögliche Lizenzbedingungen. In Eurer Ausarbeitung sollte dann noch deutlich werden, was Eure Meriten einer funktionierenden Lösung sind und an welchen Stellen Ihr schon vorher vorhandene Funktionalität verwenden.

Bitte beachtet auch die [Lizenz](https://github.com/informatiCup/informatiCup2022/blob/main/Bahn-Simulator/LICENSE) des Codes, diese müsst ihr einhalten.

Ich wünsche euch und allen Teilnehmern ein gesegnetes Weihnachtsfest!
