### ISSUE TITLE
Tests sind wieder ausgesetzt?

### ISSUE THREAD

**Issue by lukas2701** [informatiCup/informatiCup2022#27]
@Top-Ranger 
Die sind (zumindestens bei uns) erneut zuletzt am 22.12 durchgeführt worden. Liegt dies eventuell auch daran, dass unsere Tests bestanden wurden bzw. keine Fehler aufgetreten sind?

**Comment by bitflipp** [comment]
Laut CI hat sich die Commit-ID (festgestellt durch ```git rev-parse HEAD```) seit dem 22.12. nicht geändert. In diesem Fall bricht die Verarbeitung ab und es wird kein Eintrag in Teammates erstellt.

**Comment by lukas2701** [comment]
@bitflipp 
Vielen Dank für die schnelle Antwort.
Stimmt, ich habe völlig vergessen (auch) auf dieses Repository zu pushen. Entschuldigung.

**Comment by sedengel25** [comment]
Hi, diesbezüglich hätte ich auch noch eine Frage: Ich habe diverse Änderungen an den Files vorgenommen und dann in meinem lokalen "repo"-Ordner diese überspielt. Wenn ich mir dann mittels `git status` das Repository anschaue, werden diesen Änderungen erkannt. Dann habe ich manuell mit `git add` und `git rm` die Changes für `git commit` gestaged und anschließend gepusht. Allerdings habe ich an keiner Stelle den von euch empfohlenen push-command `git push --mirror ci@ci.informaticup.de:/repo` verwendet, da dieser mir immer gesagt hat, dass schon "Everything up-to-date" ist. Wenn ich mir mittels `git log` meine commit-Historie anschaue, sieht man, dass die Commit-ID immer geändert wurde. Ich habe die letzten beiden Tage einige Changes gemacht, der letzte Tests der CI war aber leider am 22.12. Könnt ihr mir da vielleicht weiterhelfen?

Vielen Dank im Voraus!

**Comment by bitflipp** [comment]
Die "Everything up-to-date"-Meldung macht mich etwas stutzig. Auf welchem Git-Repository habt ihr den Mirror-Push versucht? Auf einer Kopie des CI-Repositories ist das nicht sinnvoll.

**Comment by sedengel25** [comment]
Ich hab unser Git-Repository mittels `git clone ssh://ci@ci.informaticup.de:/repo` gecloned und dann den Mirror-Push im entsprechenden repo-Ordner gemacht.

**Comment by bitflipp** [comment]
Bitte versucht den Mirror-Push auf eurem "anderen" Repository - vorher committen. Damit könnt ihr den oben beschriebenen Prozess (Dateien überspielen, git-Kommandos) vermeiden und stattdessen euer Repository ins CI spiegeln (genauer und kryptischer unter https://git-scm.com/docs/git-push#Documentation/git-push.txt---mirror).

**Comment by bitflipp** [comment]
>  Ich habe diverse Änderungen an den Files vorgenommen und dann in meinem lokalen "repo"-Ordner diese überspielt

Aus der Beschreibung habe ich geschlossen, dass ihr ein zusätzliches Repository, z. B. auf GitHub benutzt. Ist dies nicht der Fall?

**Comment by sedengel25** [comment]
Sorry! Damit hatte ich den Ordner gemeint, der installiert wird, wenn man `git clone ssh://ci@ci.informaticup.de:/repo` ausführt. Wissentlich habe ich kein weiteres Repository erstellt, allerdings habe ich soeben das Repository "sedengel25/InformatiCup2022" entdeckt. Kann es damit zusammenhängen?

<img width="128" alt="Unbenannt" src="https://user-images.githubusercontent.com/94848853/147492857-8d793197-2348-45a9-bd40-ca19f4a9ebae.PNG">

**Comment by bitflipp** [comment]
Da muss ich in euer Repo auf dem Server schauen. Bitte schickt euren Teamnamen an phinau@gmail.com.

**Comment by Top-Ranger** [comment]
Gibt es hier noch Probleme oder hat sich alles soweit gelöst?

**Comment by sedengel25** [comment]
Alles gelöst, danke!:)
