### ISSUE TITLE
failed to run container: exit status 139

### ISSUE THREAD

**Issue by sedengel25** [informatiCup/informatiCup2022#28]
Hallo zusammen,

Ähnlich wie in [diesem Issue](https://github.com/informatiCup/informatiCup2022/issues/21#issue-1083823015) scheint es ein Problem mit dem Speicherbedarf zu geben. @bitflipp hatte hier kommentiert, den Speicherbedarf des eigenen Programms zu ermitteln. Leider weiß ich hier nicht genau, wie das funktioniert. Kann mir hier jemand weiterhelfen?

Vielen Dank im Voraus!

**Comment by bitflipp** [comment]
Maßgeblich ist der Speicherverbrauch im Container. Startet einen Container mit
```
docker run --rm --interactive --memory 2g --memory-swap 2g --cpus 2.000 --network none [Identifier eures Images] < [Pfad zu eurer Eingabedatei]
```
und prüft (während der Container läuft) mit ```docker stats``` den Resourcenverbrauch.

Beachtet in diesem speziellen Fall: Code 139 zeigt einen fehlerhaften Speicherzugriff (-> SIGSEGV) an, nicht etwa, dass der Speicher ausgegangen ist.

**Comment by sedengel25** [comment]
Danke Philipp für die schnelle Antwort!
