### ISSUE TITLE
Abzugebende PDFs

### ISSUE THREAD

**Issue by sedengel25** [informatiCup/informatiCup2022#30]
Hallo zusammen,

wir wollten noch einmal fragen, welche PDFs grundsätzlich abzugeben sind, damit die Abgabe auch berücksichtigt wird?

Da wir dieses Projekt im Rahmen eines Kurses belegen, für den wir auch einen Report schreiben müssen, haben wir versucht die Anforderungen etwas zu vereinen. Dieser Report enthält u.a. alle Unterpunkte der "Theoretischen Ausarbeitung" sowie einen großen Hauptteil, in dem der eingereichte Code im Detail erklärt wird. Der Code ist außerdem auch ausführlich kommentiert. Derzeit gibt es weder ein eigenes Kapitel bzgl. der Softwarearchitektur noch ein Handbuch, weshalb wir fragen wollten, ob diese unabdingbar sind, damit die Abgabe überhaupt bewertet wird oder ob das Fehlen einfach zu Abzügen in der Bewertung führt?

Vielen Dank im Voraus und nochmal vielen Dank für eine wirklich coole Aufgabe!

**Comment by Top-Ranger** [comment]
Die Bewertung besteht aus allen in der Checkliste erwähnten Aspekten. Wenn einige fehlen (wie z.B. eine Betrachtung der Softwarearchitektur) wird dieser Aspekt halt entsprechend schlecht bewertet - wodurch die Chance, ins Finale zu kommen, entsprechend niedrig ist (die letzten Jahre waren im Finale nur Teams, die alle Aspekte aus der Checkliste erfüllt haben). Bei sehr vielen guten Abgaben kann ich euch zudem nicht garantieren, dass nicht-vollständige Abgaben genauer betrachtet werden. Dementsprechend würde ich euch extrem nahelegen, die fehlenden Aspekte noch nachzuholen (zumal die Dozent*in die entsprechenden Kapitel einfach überspringen kann).

**Comment by sedengel25** [comment]
Alles klar, vielen Dank!
