### ISSUE TITLE
Neue Testinstanz

### ISSUE THREAD

**Issue by sedengel25** [informatiCup/informatiCup2022#31]
Hallo,

bzgl. der aktuellen Instanz wollte ich fragen, welcher Output von unserem Programm denn erwartet wird, damit die CI keinen error ausgibt? 

Vielen Dank im Voraus und viele Grüße!

**Comment by Top-Ranger** [comment]
Moin,

erwartet wird - wie bei jeder der [Spezifikation](https://github.com/informatiCup/informatiCup2022/blob/main/informatiCup%202022%20-%20Abfahrt!.pdf) entsprechenden Eingabe - eine korrekte Ausgabe [entsprechend der Aufgabenstellung](https://github.com/informatiCup/informatiCup2022/blob/main/informatiCup%202022%20-%20Abfahrt!.pdf).
Eine Ausgabe ist korrekt, falls diese (zusammen mit der Eingabe) vom [Simulator](https://github.com/informatiCup/informatiCup2022/tree/main/Bahn-Simulator) akzeptiert wird.

**Comment by sedengel25** [comment]
Hi,

ich hatte nur deshalb gefragt, weil mir die derzeitige Input-Instanz unklar ist. Unter "Details" sieht die Instanz wie folgt aus:

> [Stations]
> L1 2
> #this is a comment
> Train 2
> 
> 
> [Lines]
> L1 P2 L1 3.14 1
> 
> #this is also a comment
> l1 P2 Train 4 1
> 
> [Trains]
> Trains P2 5.5 30
> [Passengers]
> P1 P2 L1 3 3
> [Trains]
> Train * 0.9999999 50
> #we are in commentopolis! 🌃
> [Stations]
> P2 2
> 
> [Passengers]
> 
> 
> 
> 
> 
> p1 P2 Train 10 3

In meinen Augen stellt diese Instanz keine "zulässige" Instanz (gemäß der Definition der Eingabe) dar. Wäre dann ein korrekter Output einfach eine Datei, die "[Passagiere]" und "[Trains]" jedoch ohne jegliche Information über Depature, Boarding etc. enthält?

**Comment by lukas2701** [comment]
@Top-Ranger @AlexPaar @MichaelChat 
Ich schließe mich der Frage an.
Der Bahnsimulator erkennt z.B. die Passagiere P1 usw. als vollwertige Passagiere an, die weiteren Definitionen (abgesehen der ID) von diesen sind jedoch Unsinn. Bei den Strecken usw. ist das genauso. 
Somit ist es auch nicht möglich einen validen Fahrplan für diese zu erstellen.

**Comment by Top-Ranger** [comment]
So wie ich es sehe widerspricht die Datei an keiner Stelle die Aufgabenstellung, auch wenn sie etwas unorthodox aussieht. Gibt es irgendetwas spezifisches, wo ihr meint, dass sie der Aufgabe widerspricht?

**Comment by Top-Ranger** [comment]
@lukas2701 Ich sehe in der Datei insgesamt 2 Passagiere: *P1* und *p1*. Wo ist da das Problem?

**Comment by lukas2701** [comment]
@Top-Ranger 
`P1 P2 L1 3 3`
Ein Passagier soll von P2 nach L1 gefahren werden?

**Comment by Top-Ranger** [comment]
@lukas2701 Ja.

**Comment by lukas2701** [comment]
@Top-Ranger 
Ahhhhhhh.
