### ISSUE TITLE
CI-System: No dockerfile found (ohne diese geändert zu haben)

### ISSUE THREAD

**Issue by lukas2701** [informatiCup/informatiCup2022#32]
@Top-Ranger @bitflipp 
Das CI-System gibt den Error `failed to build image: no Dockerfile` an uns zurück.
Wir haben das Repository natürlich geändert und gepusht usw., aber die `dockerfile` hingegen nicht angefasst.
Zuvor hatten wir erfolgreiche Tests.
Wie kann das sein?
(Ich bin etwas verwirrt)

**Comment by bitflipp** [comment]
`docker build` akzeptiert undokumentiert (https://docs.docker.com/engine/reference/commandline/build/) auch `dockerfile` als Dockerfile-Standardname. Das CI jetzt auch. Euer Durchlauf wurde wiederholt.

**Comment by lukas-ayet** [comment]
@bitflipp
Darf ich fragen wieso das CI-System unsere dockerfile dann zuvor immer akzeptiert hat?

**Comment by lukas2701** [comment]
@bitflipp 
Darf ich fragen wieso das CI-System dann unsere dockerfile zuvor immer akzeptiert hat?

**Comment by bitflipp** [comment]
Eine heute veröffentlichte Logik prüft die Existenz der Dockerfile im Vorfeld. Bis dahin wurde lediglich der Inhalt einer existierenden Dockerfile den Details hinzugefügt (mit `cat`) und die Prüfung der Existenz `docker build` überlassen, mit dem Ergebnis einer schlecht lesbaren Fehlermeldung. Ihr werdet die Details-Sektion `Dockerfile contents` bemerken, die vorher nicht da war, obwohl ihr ein Dockerfile (oder vielmehr ein dockerfile :o)) hattet.
