### ISSUE TITLE
Fehler: failed to determine commit ID: no branches

### ISSUE THREAD

**Issue by lukas2701** [informatiCup/informatiCup2022#33]
@AlexPaar @bitflipp @Top-Ranger 
Das CI-System gibt folgende Fehlermeldung zurück:
`failed to determine commit ID: no branches`

Wir haben wie sonst auch auf ganz normalem Wege auf unser Repository gepusht. 
Woran könnte dieser Fehler liegen?

**Comment by bitflipp** [comment]
Die Bestimmung des "Haupt-Branches" war fehlerhaft. Danke.
