### ISSUE TITLE
Wie richtet man git und ssh auf anderen Betriebssystemen ein

### ISSUE THREAD

**Issue by ErdoganSeref** [informatiCup/informatiCup2022#8]
Ich finde keine Beschreibung zu anderen Betriebssystemen wie z. B. MacOs oder Linux.

**Comment by ErdoganSeref** [comment]
Ich hab unter dem .ssh Directory kein config Directory. Der key ist direkt
im .ssh Verzeichnis.

Marcus Soll ***@***.***> schrieb am Fr., 29. Okt. 2021, 19:40:

**Comment by Top-Ranger** [comment]
Es handelt sich dabei um eine einfache Text-Datei. Du kannst sie einfach anlegen (achte darauf, **keine** Dateiendung zu haben). Dort kannst du dann den Pfad eintragen.

**Comment by ErdoganSeref** [comment]
Also soll ich im Verzeichnis .ssh touch config machen und in die config
datei den Pfad zu meinem public ssh Schlüssel eintragen?

Am Fr., 29. Okt. 2021 um 22:04 Uhr schrieb Marcus Soll <
***@***.***>:

**Comment by Top-Ranger** [comment]
Ja, zum Beispiel so

**Comment by ErdoganSeref** [comment]
Der Pfad ist in der Datei ssh_config eingetragen allerdings war ein #
davor. Daher habe ich in der Zeile wo sich der erstellte Schlüssel befindet
das # entfernt. Aber das hat nichts gebracht.

Am Fr., 29. Okt. 2021 um 22:04 Uhr schrieb Marcus Soll <
***@***.***>:

**Comment by ErdoganSeref** [comment]
Können wir uns per Videocall treffen, um das Problem zu lösen? Ich denke
das geht schneller.

Am Fr., 29. Okt. 2021 um 22:04 Uhr schrieb Marcus Soll <
***@***.***>:

**Comment by ErdoganSeref** [comment]
Könnte es sein das der Fehler auftritt, weil der public key nicht im Server
eingetragen ist? In dem folgenden Link wird das als Ursache genannt.
https://stackoverflow.com/questions/44363537/gitlab-ci-ssh-permission-denied-publickey-password

Am Fr., 29. Okt. 2021 um 22:04 Uhr schrieb Marcus Soll <
***@***.***>:

**Comment by bitflipp** [comment]
Seltsam. Bitte die Ausgabe von `ls -lAR ~/.ssh` (unter Bash) posten.

**Comment by ErdoganSeref** [comment]
/home/erdogan/.ssh:
insgesamt 20
-rw-r--r-- 1 erdogan erdogan   0 30. Okt 20:52 authorized_keys
-rw-r--r-- 1 erdogan erdogan  91 31. Okt 13:57 config
-rw------- 1 erdogan erdogan 464 30. Okt 21:00 id_ed25519
-rw-r--r-- 1 erdogan erdogan 110 30. Okt 21:00 id_ed25519.pub
-rw-r--r-- 1 erdogan erdogan   0 30. Okt 20:54 id_rsa
-rw------- 1 erdogan erdogan 910 31. Okt 13:49 known_hosts
-rw-r--r-- 1 erdogan erdogan 646 27. Okt 17:18 known_hosts.old

Am So., 31. Okt. 2021 um 15:30 Uhr schrieb Philipp Naumann <
***@***.***>:

**Comment by Top-Ranger** [comment]
Moin,

drei Punkte dazu:
1. Den Inhalt welcher Datei hast du bei Teammates angegeben?
2. Die Datei ```id_rsa``` hat eine Größe von 0. Das heißt, sie hat keinen Inhalt und keinen key.  Das sollte so eigentlich nicht sein. Da eine entsprechende .pub-Datei fehlt würde ich empfehlen, die einfach zu löschen (damit sie keine Probleme machen kann)
3. Kannst du noch einmal ```GIT_SSH_COMMAND="ssh -v" git clone ci@ci.informaticup.de:/repo``` unter bash aufrufen?

**Comment by ErdoganSeref** [comment]
Den Inhalt der Datei id_ed25519.pub.

Klone nach 'repo' ...
OpenSSH_8.8p1, OpenSSL 1.1.1l  24 Aug 2021
debug1: Reading configuration data /home/erdogan/.ssh/config
debug1: /home/erdogan/.ssh/config line 1: Applying options for
ci.informaticup.de
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Connecting to ci.informaticup.de [85.214.244.186] port 22.
debug1: Connection established.
debug1: identity file /home/erdogan/.ssh/id_ed25519 type 3
debug1: identity file /home/erdogan/.ssh/id_ed25519-cert type -1
debug1: identity file /home/erdogan/.ssh/id_ed25519 type 3
debug1: identity file /home/erdogan/.ssh/id_ed25519-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.8
debug1: Remote protocol version 2.0, remote software version OpenSSH_8.2p1
debug1: compat_banner: match: OpenSSH_8.2p1 pat OpenSSH* compat 0x04000000
debug1: Authenticating to ci.informaticup.de:22 as 'ci'
debug1: load_hostkeys: fopen /home/erdogan/.ssh/known_hosts2: No such file
or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or
directory
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ssh-ed25519
debug1: kex: server->client cipher: ***@***.*** MAC:
<implicit> compression: none
debug1: kex: client->server cipher: ***@***.*** MAC:
<implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: SSH2_MSG_KEX_ECDH_REPLY received
debug1: Server host key: ssh-ed25519
SHA256:Df9LHxLqH/SvBpMiR2y9V3Y8zfma29o4AGC3qA/lbQo
debug1: load_hostkeys: fopen /home/erdogan/.ssh/known_hosts2: No such file
or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or
directory
debug1: Host 'ci.informaticup.de' is known and matches the ED25519 host key.
debug1: Found key in /home/erdogan/.ssh/known_hosts:3
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 134217728 blocks
debug1: Will attempt key: /home/erdogan/.ssh/id_ed25519 ED25519
SHA256:5SACf9kmiV0F52MVCKOllRbXGERoG7PKX9Cv2TBEdgw explicit
debug1: Will attempt key: /home/erdogan/.ssh/id_ed25519 ED25519
SHA256:5SACf9kmiV0F52MVCKOllRbXGERoG7PKX9Cv2TBEdgw
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,
***@***.***
,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,
***@***.***>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Offering public key: /home/erdogan/.ssh/id_ed25519 ED25519
SHA256:5SACf9kmiV0F52MVCKOllRbXGERoG7PKX9Cv2TBEdgw explicit
debug1: Authentications that can continue: publickey
debug1: Offering public key: /home/erdogan/.ssh/id_ed25519 ED25519
SHA256:5SACf9kmiV0F52MVCKOllRbXGERoG7PKX9Cv2TBEdgw
debug1: Authentications that can continue: publickey
debug1: No more authentication methods to try.
***@***.***: Permission denied (publickey).
fatal: Konnte nicht vom Remote-Repository lesen.

Bitte stellen Sie sicher, dass die korrekten Zugriffsberechtigungen bestehen
und das Repository existiert.



Am So., 31. Okt. 2021 um 21:12 Uhr schrieb Marcus Soll <
***@***.***>:

**Comment by Top-Ranger** [comment]
Moin,

aus dem Debug sehe ich jetzt, dass der Schlüssel von ssh gefunden wird:
```
debug1: identity file /home/erdogan/.ssh/id_ed25519 type 3
```
Der Fehler scheint jetzt noch zu sein, dass du nicht den Schlüssel in teammates eingetragen hast, sondern stattdessen die Checksumme. Sobald du den **öffentlichen Schlüssel** in Zoom eingetragen hast (inhalt von ```id_ed25519.pub``` ohne Zeilenumbrüche) solltest du Zugriff auf das Repo haben.

Siehe auch [das Update im icupci-Tutorial](https://github.com/informatiCup/informatiCup2022/blob/main/ICUPCI.md#wie-sieht-der-%C3%B6ffentliche-ssh-schl%C3%BCssel-aus).

Kannst du hier kurz Rückmeldung geben ob das klappt?

**Comment by Top-Ranger** [comment]
Moin, funktioniert der Zugriff jetzt?

**Comment by Top-Ranger** [comment]
Da keine weiteren Fragen gekommen sind gehe ich davon aus, dass das Problem behoben ist.
Wenn noch irgendwo Probleme auftreten kannst du gerne das issue wieder öffnen.
