### ISSUE TITLE
Kann repo nicht klonen

### ISSUE THREAD

**Issue by ErdoganSeref** [informatiCup/informatiCup2022#9]
Nachdem ich die Schritte befolgt habe, um ssh und git auf Linux einzurichten habe ich folgende Fehlermeldung bekommen.

git clone ssh://ci@ci.informaticup.de:/repo
Klone nach 'repo' ...
ci@ci.informaticup.de: Permission denied (publickey).
fatal: Konnte nicht vom Remote-Repository lesen.

Bitte stellen Sie sicher, dass die korrekten Zugriffsberechtigungen bestehen
und das Repository existiert.

**Comment by Top-Ranger** [comment]
Siehe https://github.com/informatiCup/informatiCup2022/issues/8
